name: tag-workflow
on:
  push:
    tags:
      - v*.0
jobs:
  Run-tagged-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
            - name: Install required dependencies
              run: yarn
            - name: Grant access for script files
              run: chmod -R +x scripts
            - name: Build packages
              run: lerna run build
            - name: Run linters
              run: lerna run lint
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build docker image
        run: docker build . -f root.Dockerfile -t bet --no-cache
      - name: docker push
        run: |
          docker tag bet ${{ secrets.DOCKER_USER }}/bet:${{github.sha}}
          docker push ${{ secrets.DOCKER_USER }}/bet:${{github.sha}}
      #        run: docker push "bet/bet-common:${{github.sha}}"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
